### ISSUE TITLE
Collection operation error with nested functions

### ISSUE THREAD

**Issue by neeasade** [techniq/odata-query#12]
Say I want to have a case insensitive search on a property in a nested collection of items, where what I'm  filtering is formed like:

DTO:
```
name: "<name>"
items: "<object array with property to search on 'searchProp'>"
```

So I form a filter like (where search is a search string):
```
        const filter = {
            or: {
                "toupper(name)": {
                    contains: search.toUpperCase()
                },
                "items": {
                    any: {
                        "toupper(searchProp)": {
                            contains: search.toUpperCase()
                        }
                    }
                }
            }
        }

        buildQuery({filter});
```

Currently the second `toupper` (in the any call) is prefixed with the lambda variable, resulting in an invalid call -- instead searchProp should be prefixed. 

Result : `$filter=contains(toupper(name),'C') or items/any(a:contains(a/toupper(searchProp),'C')`

Which should actually be: `$filter=contains(toupper(name),'C') or items/any(a:contains(toupper(a/searchProp),'C')`

edit: I'm rather new to odata-queries, please do let me know if there is a prefered way to do this nested collection type of query.

**Comment by techniq** [comment]
Hmm, I created a simpler test case to try to demonstrate the problem (I removed the `or` condition).  Does this look to capture what you are trying to do?

![image](https://user-images.githubusercontent.com/177476/35898643-caebaf28-0b95-11e8-85aa-8b855a83139e.png)

Ultimately the problem is I automatically prefix what I assume to be the collection's property name with a generated lambda variable (first letter of property name converted to lower case) which did not take into account when a function was used.

I released `5.1.1` that should resolve this issue.  Let me know if it works as you intended.

**Comment by neeasade** [comment]
Works great, thanks

**Comment by fabio-b** [comment]
@techniq I ran into something similar but with `indexOf` function.

Input:
```
{
  Item: {
    any: {
      indexof(tolower(Name), 'gead'): {
        eq: -1
      }
    }
  }
}
```
Outputs -> Item/any(p:indexof(p/tolower(Name), 'adf') eq -1)

Expecting -> Item/any(p:indexof(tolower(p/Name), 'adf') eq -1)

Is there a syntax to achieve the above output? I tried switching `indexof` with `tolower` but indexof requires 2 parameters. Thanks.
