### ISSUE TITLE
Cannot group filter with or operator

### ISSUE THREAD

**Issue by imhotepjs** [techniq/odata-query#30]
_Request_

    "filter": {
        or: [{
            PropName: { gt: 5 },
            and: [
                { SomeProp: 1 },
                { AnotherProp: 2 }
            ]
        }

_Expected_

$filter=((PropName gt 5 **or** ((SomeProp eq 1) and (AnotherProp eq 2))))

_Response_

$filter=((PropName gt 5 **and** ((SomeProp eq 1) and (AnotherProp eq 2))))

**Comment by techniq** [comment]
Each object/item in the array is `or`'d together, so instead of:

```js
{
  filter: {
    or: [{
        PropName: { gt: 5 },
        and: [
            { SomeProp: 1 },
            { AnotherProp: 2 }
        ]
    }]
  }
}
```

the `{ PropName: { gt: 5 } }` should be in a different object than the `{ and: [ ... ] }` like so:
```js
{
  filter: {
    or: [
      { PropName: { gt: 5 } },
      { and: [
            { SomeProp: 1 },
            { AnotherProp: 2 }
        ]
    }]
  }
}
```

You can paste this into my [odata-query sandbox](https://codesandbox.io/s/108k51nzm3) if you need to test our the result of some queries.  See also some of the tests (like [this one](https://github.com/techniq/odata-query/blob/master/src/index.test.js#L219-L234)).  Hope that helps.
